server:
  port: 8999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01?serverTimezone=GMT&characterEncoding=utf-8
    hikari:
      username: root
      password: 123456
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/